name: Release / Cherry Pick

on:
  workflow_dispatch:
    inputs:
      prs:
        description: "The PR numbers to be cherry-pick"
        type: string
        required: true

env:
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  main:
    name: Run cherry-pick
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - shell: bash
        run: |
          ./scripts/cp.sh ${GITHUB_REF_NAME} ${{inputs.prs}}
