name: Release

on:
  push:
    branches:
      - master
      - release/v*

permissions:
  contents: write
  pull-requests: write

jobs:
  release:
    runs-on: ubuntu-latest
    environment: test
    env:
      ACTIONS_RUNNER_DEBUG: true
    steps:
      - uses: googleapis/release-please-action@v4
        with:
          target-branch: ${{ github.ref_name }}
          release-type: terraform-module
