name: Release

on:
  push:
    branches:
      - release/v*

permissions:
  contents: write
  pull-requests: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v3
        with:
          default-branch: release/v2.0
          release-type: terraform-module
          extra-files: |
            variables.tf
