name: Release

on:
  push:
    branches:
      - release/v*

permissions:
  contents: write
  pull-requests: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@v4
        with:
          release-type: terraform-module
          extra-files: |
            variables.tf
